#!/bin/bash/env ruby

puts ""
quit = true
while quit
  input = gets.chomp
  case input.downcase
  when "help"
    puts "valid commands are list, quit"
  when "list"
    puts "tic_tac_toe"
  when "tic tac toe"
    load "bin/tic_tac_toe.rb"
  when "quit"
    quit = false
  else
    puts "please type in a valid command"
    puts "type in help for help"
  end
end
